### ISSUE TITLE
Solved: unexpected character / Unexpected token <

### ISSUE THREAD

**Issue by Comenius** [blueimp/jQuery-File-Upload#1989]
Hey guys,

After few hours testing i've figured out how to resolve the issue named in the title.
Maybe it's your solution too. Otherwise you're just as smart as before.

My page running under mod_rewrite and some rewriterule's. 
So i created a .htaccess in the plugins dir and turned off the rewrite enginge.
(RewriteEngine Off)

Good luck,
Comenius

**Comment by JialuZhang** [comment]
@Comenius 

In your posted configuration,
```
RewriteEngine Off
```
the line "RewriteEngine Off“ is a silent misconfiguration. This means adding it to your system will not change any system behavior.
"RewriteEngine Off" is introduced by Apache to explicitly disable all "RewriteRule" and "RewriteCond".
That is to say, if you include multiple "RewriteRule" and "RewriteCond" parameters in your configuration, then instead of commenting them all, you can explicitly set “RewriteEngine Off” to disable all "RewriteRule".
More importantly, the default value of “RewriteEngine" is already an "off", so adding “RewriteEngine off" is quite unnecessary and it may cause confusion to users.
Since herein there is no "RewriteRule" in this directory, deleting “RewriteEngine Off” would be ideal.
Related Apache source code snippet:
```
run_rewritemap_programs(server_rec *s , apr_pool_t *p){
if (conf->state == ENGINE_DISABLED) { // usage of "RewriteEngine"
  return APR_SUCCESS; // early return
rewritemap_program(...); // usage of "RewriteRule" 
}
```
