### ISSUE TITLE
Large number of files - slow initialisation in Chrome and Safari

### ISSUE THREAD

**Issue by minioak** [blueimp/jQuery-File-Upload#3166]
I'm using the jquery file upload api - (not the ui) - with no processing or preview images, but when selecting a large number of images (testing with 580 images - around 360Kb each), the browser (Safari and Chrome) locks up the UI and gives you the spinning ball treatment while it's adding the files to the upload queue.

Firefox has virtually no delay with the same set of 580 files, and you instantly see the add event firing, and the ui updating appropriately.

Any suggestions?

**Comment by blueimp** [comment]
Revisiting this - selecting a large number of files can definitely freeze the UI (in my tests in Chrome, Safari and Firefox).
Since this plugin does not make use of web workers, all processing is done on the main thread.
At the moment I don't see a good way to make use of web workers (which would require copying data between worker and main threads), nor another way to significantly improve performance for a large file selection.
So, closing as inconclusive but not feasably fixable.
