### ISSUE TITLE
DOCUMENTATION breaking changes when migrating from 9.x.x to 10.x.x?

### ISSUE THREAD

**Issue by wumke** [blueimp/jQuery-File-Upload#3540]
Hi, I want to update but cannot find a list with breaking changes... (sorry if I overlooked it)
Please put breaking changes (and new features and fixes) in the release notes so that they appear in the github overview of releases.

**Comment by blueimp** [comment]
Hi @wumke,
this project never had any release notes. Mostly because this is largely a one-person effort, not because proper release notes are not useful.

The closest thing to release notes is the lost of commit messages on the master branch:
https://github.com/blueimp/jQuery-File-Upload/commits/master

There were no breaking changes to the JS library, but the removal of the obsolete bower.json config file, the removal of the alternative demo versions (e.g. for AngularJS and jQuery UI) and the addition of End-To-End Tests where satisfying reasons to bump the major version number.

**Comment by wumke** [comment]
Thanks for the quick response!

I'm migrating a project from bower to npm, and took that as an opportunity to update the dependecies... but updating to higher major versions scares me if i have no clue what will happen :-)

I know it takes a lot of time to maintain a project... (also doing it myself) I'd suggest you add a  simple 'no breaking changes' at major release bumps.

**Comment by brandonkelly** [comment]
Changelogs don’t have to be a lot of work, and can save you time as the maintainer as well. Check out [keepachangelog.com](https://keepachangelog.com/en/1.0.0/) when you have a chance – there are a few useful tips there.

**Comment by blueimp** [comment]
Thanks for the link @brandonkelly.
I like the suggestion of keeping an `Unreleased` section to reduce overhead.
