### ISSUE TITLE
Request timeout while uploading large file (4MB)

### ISSUE THREAD

**Issue by bnfd** [blueimp/jQuery-File-Upload#3550]
I get "Request timeout" while trying to upload a large file (~4MB) or multiple smaller files to the server. Basically anything that takes too long. 
I have checked and raised the limits of php.ini but didn't make any difference. 
Is there anywhere else that I should be looking?

**Comment by blueimp** [comment]
I cannot provide support for your backend configuration, but `4MB` is not particularly large in my view and should be handled well by most default PHP configurations.

You could compare this with the provided Docker configuration (which uses PHP for the backend) in this project.
Given a Docker setup, you can run it with `docker-compose up -d` and then access the demo on http://localhost.

I'm closing this since this doesn't seem to be a problem with the project itself, but feel free to post additional comments.
Please also see #2190.
