### ISSUE TITLE
jquery.fileupload-angular.js

### ISSUE THREAD

**Issue by david-hollifield** [blueimp/jQuery-File-Upload#3552]
I was updating my fork with the latest changes and noticed that jquery.fileupload-angular.js has been removed. Is that file no longer supported?

**Comment by blueimp** [comment]
Yes, the AngularJS version is no longer supported, I wrote a related comment here: https://github.com/blueimp/jQuery-File-Upload/issues/3540#issuecomment-562064234

That being said, since the JQuery File Upload API didn’t change, you can use the AngularJS file of previous versions and it should work as before.

**Comment by david-hollifield** [comment]
Makes sense. Thanks!
