### ISSUE TITLE
JSON.parse: unexpected non-whitespace character after JSON data at line 1 column 433 of the JSON data

### ISSUE THREAD

**Issue by khanks** [blueimp/jQuery-File-Upload#3615]
'Add Files' works fine, displaying the thumbnail. This happens when the 'Start' button is pressed. I'm using **your code* (blueimp/jQuery-File-Upload)*, not mine, and added your code from https://github.com/blueimp/jQuery-File-Upload/wiki/PHP-MySQL-database-integration . The only difference is that I'm storing the actual image content in the database ( I see you don't do that in your example). We store images in the DB and I'm not going to have a conversation about whether or not that should be done. It's what's been dictated. This image is 327kb.
I've been using a simple php/ajax upload and it works fine. We simply liked your interface better. 
Firefox 73, 64-bit
PHP 7.2, MariaDB 10.1.37

If you can help, great. If not, we'll use something else.

**Comment by blueimp** [comment]
Hi @khanks,
unfortunately, the PHP MySQL integration in the Wiki is unsupported - that means the code posted there was tested once, 7 years ago and never touched again - there's no guarantee it still works as expected.

That being said, if you post the actual JSON response, that would be helpful.
You could also run it through an online JSON linter to help identify the issue, e.g. https://jsonlint.com/

**Comment by khanks** [comment]
Thank you for your response. I thought of that until I noticed that it
appears to be including the actual image as part of the json response. So
that makes it pretty big to paste into a linter. My debugger is not working
right now (side issue), but I have echoes around my SQL code and it never
gets there. So I found that strange as well. Thank you anyway.

**Comment by blueimp** [comment]
That sounds like you’re storing the image data in the title or description, or another field returned in the JSON response.

I do not recommend returning binary data in the JSON response, so the easiest fix is to either store the image data in a different field of the MySQL table or adjust the PHP code to not return that field in the JSON response.

If you absolutely have to return binary data in a JSON response, you could consider the following two options:

1. Send the binary data as `base64` encoded string, which can then be sent as normal JSON object properties.
2. Instead of using a content-type of `application/json`, you could send `multipart/form-data`, which would allow you to send the JSON and binary data separately, see this StackOverflow answer for further info: https://stackoverflow.com/a/28080392

Option two is definitely more development effort on both server- and client-side, but has the benefit of not requiring the base64 conversion overhead.

I would still definitely recommend you to not send the binary data in the upload response at all though.

**Comment by blueimp** [comment]
Closing this as resolved.
