### ISSUE TITLE
Using Google Storage with Signed URLs cause different filesize after upload

### ISSUE THREAD

**Issue by UtkuBulkan** [blueimp/jQuery-File-Upload#3624]
I am facing a very interesting situation, with Signed-urls and Google Storage.

When I use the following code, it uploads to Google Storage yet, the file size is different than the original file size, and the file seems larger than the original. (To be precise the original file size is 272.74 KB but uploaded file size is 273.14 KB)

```
$(function () {
  $("#fileupload").fileupload({
    type: 'PUT',
    sequentialUploads: false,

    submit: function(e, data) {
        var $crf_token = $('[name="csrfmiddlewaretoken"]').attr('value');
        var $this = $(this);
        $.each(data.files, function(index, file) {
            // pack our data to get signature url
            var formData = new FormData();
            formData.append('filename', file.name);
            formData.append('type', file.type);
            formData.append('size', file.size);

            // Step 3: get our signature URL
            $.ajax({
                url:  '/api/upload/signedurl/',
                type: 'POST',
                processData: false,
                contentType: false,
                dataType: 'json',
                headers: {
                    'X-CSRFToken': Cookies.get('csrftoken'),
                },
                primary_data: data,
                data: formData
            }).done(function (data) {
                this.primary_data.headers={'Content-Type': file.type};
                this.primary_data.uuid = data.uuid;
                this.primary_data.title = data.filename;
                this.primary_data.url = data.signed_url;
                this.primary_data.jqXHR = $this.fileupload('send', this.primary_data);
            });
        });
    },
```

Yet, When I use the following pseudo code  with only XMLHTTPRequest :

```
xhr.open("PUT", data.signed_url);
xhr.setRequestHeader('Content-Type', file.type);
xhr.send(file);
```

It uploads to Google Storage fine using the signed url and resulting with expected file size.

How can this be ?

**Comment by blueimp** [comment]
So I guess this is related to your first post here: #3621 

You're submitting a `FormData` object (which represents a `multipart/form-data` encoded message payload) in your first example.
However Google Storage expects a plain `File` object, so you should instead set `data.files[index]` as `data` option for your `$.ajax` call.

Hope this helps.

Since this doesn't have much to do with an issue in jQuery File Upload, I'm closing this ticket.
Please note that I don't provide official support and might close future tickets without comment.
See also #2190
