### ISSUE TITLE
data.context UI detached from DOM after jqXHR.abort()

### ISSUE THREAD

**Issue by ChristophNeuner** [blueimp/jQuery-File-Upload#3625]
Hello,

when I abort the uploading process with jqXHR.abort() the HTML elements in data.context are removed from the DOM and no longer visible on the website.
Is there a way to prevent this behavior?
Otherwise I had to save the elements before the abort and reattach them afterwards.
I want to build a stop/resume bahavior.

Thanks a lot in advance,

Christoph

**Comment by ChristophNeuner** [comment]
I found a solution:

```
                data.abort();
                //this prevents abort() from removing ui elements
                data.context.append($('<p/>').replaceAll($(this)));
```

**Comment by blueimp** [comment]
Removing elements from the UI when uploads are canceled is by design and part of the `fail` handler here:
https://github.com/blueimp/jQuery-File-Upload/blob/25909b05594dbd2153bd9d10a3a60e29c96f475f/js/jquery.fileupload-ui.js#L215-L272

If you wish to change this behavior you could override the fail handler.
