### ISSUE TITLE
Can the file editor show at the outer html body

### ISSUE THREAD

**Issue by voltwu** [blueimp/jQuery-File-Upload#3630]
I have a page which inserts an `iframe`,
like the below:
![QQ截图20200416162650](https://user-images.githubusercontent.com/45677662/79432950-1a214f00-7fff-11ea-9436-9413380e512d.png)

I add some a file on it.
![QQ截图20200416162744](https://user-images.githubusercontent.com/45677662/79433090-489f2a00-7fff-11ea-8451-2819886d8d9a.png)

but when I click the **edit** button, it becomes like this
![QQ截图20200416162755](https://user-images.githubusercontent.com/45677662/79433156-5ce32700-7fff-11ea-8b04-5c4d90bab07b.png)

I want to show the edit panel at the out body, not in the iframe.

**Comment by blueimp** [comment]
The image editor is not a part of jQuery File Upload, but a separate project, see also https://gumroad.com/a/75084915.

That being said, iframes are constrained to their window by design, so you will not be able to show any user interface components originating from an iframe outside of it.

A potential workaround could be implement the editor outside of the frame and pass image blobs to the frame via [postMessage](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage) protocol:
https://github.com/blueimp/jQuery-File-Upload/wiki/Cross-domain-uploads#postmessage-transport

Please also see #2190
