### ISSUE TITLE
Feature request.

### ISSUE THREAD

**Issue by precision1980** [blueimp/jQuery-File-Upload#3636]
I rewrote the function for the folder upload to accept a request with the folder path to store it. I wanted to ask to have this feature added to the file so others can use that functionality too. The one upload was great but when you're uploading to a structure that is restricted based on the user it helps a lot.

Example: in the post, send a variable, aka element value, that would say where they want the file to go. I simply added a switch statement that has 3 rules. public, private, shared. With that said. whatever the user chooses in my select element 1-3 it will upload it to the appropriate folder. I also rewrote the sessions to work with database stored PHP sessions.

**Comment by blueimp** [comment]
Thanks for your suggestion @precision1980 

The folder upload selection certainly serves a use case, but is too specific to be integrated into this library.

I think the database stored session is a good candidate for a wiki page.
The wiki editing has been restricted (due to vandalism), but since both the wiki and the comment feature here use markdown syntax, if you submit a comment with database stored session guide, I'll gladly add it to the wiki.
