### ISSUE TITLE
Mime type check (validation)

### ISSUE THREAD

**Issue by kepon85** [blueimp/jQuery-File-Upload#3644]
Hello,

I have implemented jQuery-File-Upload in file2link: https://framagit.org/kepon/file2link (demo: http://dl.zici.fr/) thanks for your work!

I'm looking to implement validation by "mime type". it seems to me more flexible / secure than a verification by file extraction (example if I ban videos it is simple to rename a toto.mpg video to toot.jpeg for the upload ... with a verification by mime that will be more complicated ...)

I would like the mime to be checked when added, before sending (to save bandwidth ...)

I tried several things without success fileuploadadded / added ... I must not succeed in finding the right syntax so that the error appears correctly ... (I am not really after a crack in javascript)

Do you have a lead for me?

Thanks in advance,
David

**Comment by blueimp** [comment]
Hi @kepon85,

while mime type detection can be more accurate than relying on the file extension, it's not necessarily more secure.

For example, you can test the limits of mime type detection with the following code sample (also added to the [Security documentation](https://github.com/blueimp/jQuery-File-Upload/blob/master/SECURITY.md#secure-file-upload-serving-configurations), which I recommend everyone using this project to read):
```php
GIF89ad <?php echo mime_content_type(__FILE__); phpinfo();
```

If you save this code as `test.php` and identify its mime type with the command-line [file](https://github.com/file/file) utility (which is included in all Linux distributions and macOS and the backend for most mime detection libraries), you get the following output:

```
$ file test.php 
test.php: GIF image data, version 89a, 8292 x 16188
```

For example, PHP will happily execute this file as PHP script, while the script will ironically detect itself as `image/gif` via the [mime_content_type](https://www.php.net/manual/en/function.mime-content-type.php) function call.

**For Security, it's important to use the same context for validation that you use for execution.**

Server configurations commonly make use of the file extension to determine which files should be handled by the PHP interpreter.
For that reason, you also want to use the file extension in your validation logic.

So instead of identifying files by their [magic bytes](https://en.wikipedia.org/wiki/List_of_file_signatures), you want to have a limited allow-list of file extensions that are safe to be stored in your upload directory.

Ideally, your upload directory is completely decoupled from the directory that is hosting your application code, e.g. by uploading to a directory that is not handled by your application server.

**Client-side file upload validation is useful for usability, but has nothing to do with security.**
So while file input fields have an [accept](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file#attr-accept) attribute and jQuery File Upload has an [acceptFileTypes](https://github.com/blueimp/jQuery-File-Upload/wiki/Options#acceptfiletypes) option, you need to keep in mind that an attacker can simply send files to your server directly (e.g. using [curl](https://curl.haxx.se/) and does not need to use your HTML form or pass your JavaScript validation.

**Comment by kepon85** [comment]
Thank you for your relevant demonstration!
I understand better!
David

**Comment by blueimp** [comment]
You're welcome. ☺️
