### ISSUE TITLE
Upload php file

### ISSUE THREAD

**Issue by DoDDnice6** [blueimp/jQuery-File-Upload#3646]
How to execute php files after uploading.  I tried open but the browser downloaded that file.  What code handles it?

**Comment by blueimp** [comment]
Hi @DoDDnice6,

to answer your question, likely the code in this file:
https://github.com/blueimp/jQuery-File-Upload/blob/master/server/php/files/.htaccess#L31

However, you most likely don't want to disable this, as it's a security feature.
Please also have a look at the [SECURITY](https://github.com/blueimp/jQuery-File-Upload/blob/master/SECURITY.md) document for this project.

**Comment by DoDDnice6** [comment]
So why is the demo website blocking uploading php files?

**Comment by blueimp** [comment]
The [demo](https://blueimp.github.io/jQuery-File-Upload/) has never accepted anything else but image files, because there was no need to accept anything beyond images, as that is sufficient for a demo.

The PHP demo included in the repo has historically accepted any file for upload for local testing purposes, but this led to [security vulnerabilities related to how Apache was configured](https://github.com/blueimp/jQuery-File-Upload/blob/master/VULNERABILITIES.md#remote-code-execution-vulnerability-in-the-php-component) on individual setups.

Technically, you can configure file uploads securely that accept any file for upload, as long as you make sure that those files can neither be executed on the server nor executed on the client (this is also explained in the [SECURITY](https://github.com/blueimp/jQuery-File-Upload/blob/master/SECURITY.md#mitigations-against-file-upload-risks) document).

**Comment by DoDDnice6** [comment]
Thank you your answer!

**Comment by blueimp** [comment]
You're welcome. ☺️
