### ISSUE TITLE
Feature Request: Pausable Uploads

### ISSUE THREAD

**Issue by bounlu** [blueimp/jQuery-File-Upload#3648]
Hi,

I am wondering if it is possible to add PAUSE/RESUME buttons for each file to control their uploading status. This is really useful when uploading multiple large files to pause some so that others are uploaded faster, i.e. prioritize files to upload. Cancelling may not be feasible since it will cause loss of time for large files that are already uploaded half-way. Another use could be when the user realizes he needs to free the overall network bandwith to upload other data in another application faster.

Thanks.

**Comment by blueimp** [comment]
Hi @bounlu,

while individual HTTP requests cannot be paused, this project already supports resumable chunked file uploads:
https://github.com/blueimp/jQuery-File-Upload/wiki/Chunked-file-uploads#resuming-file-uploads

So if you want to provide a pause functionality to your users you need to:
1. Use a server-side file upload handler that supports chunked resumable uploads
2. Enable [chunked uploads](https://github.com/blueimp/jQuery-File-Upload/wiki/Chunked-file-uploads) on the client-side 
2. Implement the UI that keeps a reference to the selected file on pause and uploads the remaining bytes on resume (see the wiki section linked above).

If you would like to maintain a fork that provides those UI changes, I'll gladly add a link to the wiki.
Since it's unlikely that I'll add those UI changes to the main project, I am closing this issue, as the required resumable uploads functionality is already implemented.
