### ISSUE TITLE
how to save as a new filename?

### ISSUE THREAD

**Issue by dadahellohello** [blueimp/jQuery-File-Upload#3660]
I use this library demo and php server to work successfully. 
now, when I upload one image file, I want save the file use post parameter filename, how to do?can someone tell me, thanks.

**Comment by blueimp** [comment]
Instead of providing the file name as POST parameter, you can change the actual file name submitted as part of the upload using the `uploadName` property - no server-side change necessary:
https://github.com/blueimp/jQuery-File-Upload/wiki/API#how-to-provide-alternative-file-names

Please also see #2190
