### ISSUE TITLE
Can i use this with native form submit

### ISSUE THREAD

**Issue by achchu93** [blueimp/jQuery-File-Upload#3686]
I have a form which is works like normal HTML form. So when it submits it sends data to php and accessible through $_FILE global parameter. Can i use this plugin without ajax? When we drag and drop it should sets the value to file input. Then we can easily access it with global $_FILE variable. Please help me. I couldn't find any doc or help on documentation section.

**Comment by blueimp** [comment]
Hi @achchu93, by default all uploads through this library will reach your server-side in the same `multipart/form-data` format as a standard HTML form uploads.

The sample PHP upload handler also uses the standard PHP `$_FILES` array:
https://github.com/blueimp/jQuery-File-Upload/blob/93467eff3721f9405758eaee3bb079f95509536b/server/php/UploadHandler.php#L1221-L1223
The `$id` passed here is `files`, since the file input field is set to `files[]` in the demo:
https://github.com/blueimp/jQuery-File-Upload/blob/93467eff3721f9405758eaee3bb079f95509536b/index.html#L111

Please also see #2190.

**Comment by achchu93** [comment]
Hello @blueimp ,

Thanks for the response. But it sends data in a Ajax request. I want it to be native form submission. Which will reload the browser. So in that case `$_FILE` variable is empty. I tried the example. But it sends ajax request.  

Please let me know whether is that correct or not.

Thanks!

**Comment by blueimp** [comment]
On some devices, you can drag and drop to the file input field (the drop needs to happen directly on the file input element), but like you said there's no way to programmatically set the file input field.

On the server-side, there's technically no difference between an AJAX style file upload vs a standard HTML form submission upload, with the exception of cross-domain file uploads requiring certain headers from the server-side, see:
https://github.com/blueimp/jQuery-File-Upload/wiki/Cross-domain-uploads

However if you absolutely want to force an HTML form submission, you can do so with the `forceIframeTransport` option:
https://github.com/blueimp/jQuery-File-Upload/wiki/Options#forceiframetransport
