### ISSUE TITLE
Individual preview

### ISSUE THREAD

**Issue by Lifamen** [blueimp/jQuery-File-Upload#3688]
Hello, I figured out how to do multiple file input fields in one form. But how to make individual preview and gallery for each input?

**Comment by blueimp** [comment]
Hi @Lifamen,

As explained in the guide [Multiple File Input Fields in One Form](https://github.com/blueimp/jQuery-File-Upload/wiki/Multiple-File-Input-Fields-in-One-Form), providing multiple file input fields can be done by adding form input fields with different `name` attributes.

If you want to handle the previews in the default User Interface differently, you could override the `_renderPreviews` function:
https://github.com/blueimp/jQuery-File-Upload/blob/93467eff3721f9405758eaee3bb079f95509536b/js/jquery.fileupload-ui.js#L499-L503
You can identify the different file selections via `data.paramName`, which will be set to the file input field `name` property.

Since the Gallery is provided by [blueimp Gallery](https://github.com/blueimp), you can read the documentation on how to do link grouping there:
https://github.com/blueimp/Gallery#container-ids-and-link-grouping

You can then adjust the download template `data-gallery` attribute accordingly:
https://github.com/blueimp/jQuery-File-Upload/blob/93467eff3721f9405758eaee3bb079f95509536b/index.html#L283
https://github.com/blueimp/jQuery-File-Upload/blob/93467eff3721f9405758eaee3bb079f95509536b/index.html#L290

Please also see #2190
