### ISSUE TITLE
Preview photos larger than 10M

### ISSUE THREAD

**Issue by PhilCliv** [blueimp/jQuery-File-Upload#3693]
It seems that it cannot handle preview of images larger than 10M before upload. Am I missing something?  
Thanks!

**Comment by blueimp** [comment]
That's the default setting, deliberately chosen since processing larger images takes longer for the browser to perform.
You can change it though:
https://github.com/blueimp/jQuery-File-Upload/blob/1363486f8855d6ca9c28be53a93f27e1d9db8338/js/jquery.fileupload-image.js#L128-L129
https://github.com/blueimp/jQuery-File-Upload/wiki/Options#loadimagemaxfilesize
