### ISSUE TITLE
Dropzone not being destroyed

### ISSUE THREAD

**Issue by Eseperio** [blueimp/jQuery-File-Upload#3731]
How to reproduce:

Load a page with fileUpload via ajax in a modal. Close it and then reopen it again reloading content via ajax (in my case each modal is a different page). 
Do not set a dropZone. 

What is happening:
Drop event is being attached to document as many times as instances of fileUpload are created. They are never destroyed or reset before initialize a new instance.
This cause files to be uploaded to previous  opened destinations or uploaded to same place multiple times.

New instances should take care about existing drop events in the document.

**Comment by blueimp** [comment]
I think the use case you're describing doesn't allow jQuery File Upload to keep track of its dropZone, since you simple remove the element it's attached to, without properly destroying the instance.
I recommend you to use the deinitialization function before removing the modal:
https://github.com/blueimp/jQuery-File-Upload/wiki/API#deinitialization
