### ISSUE TITLE
Images still failing to upload (Not solved by #3639)

### ISSUE THREAD

**Issue by bourbonneat** [blueimp/jQuery-File-Upload#3748]
[#3639](https://github.com/blueimp/jQuery-File-Upload/issues/3639) implies that this issue can be resolved by updating the blueimp plugin to 10.31.0 or reverting the Load Image plugin to a version < 5. I've tried both, and images with certain EXIF metadata still won't successfully upload. Clearing this EXIF metadata allows successful uploads, but we can't force customers to do this.

**Comment by blueimp** [comment]
Could you provide sample images for which you can reproduce this issue on the [demo](https://blueimp.github.io/jQuery-File-Upload/)?

**Comment by blueimp** [comment]
If you have issues with images failing to be processed due to specific EXIF metadata, please provide a sample image that throws errors when loaded on the [Load Image demo](https://blueimp.github.io/JavaScript-Load-Image/) and file an issue in the [JavaScript-Load-Image project](https://github.com/blueimp/JavaScript-Load-Image/).
Please make sure that you use the latest versions of both the [JavaScript-Load-Image library](https://github.com/blueimp/JavaScript-Load-Image/) as well as this project.
